name: Build

on:
  release:
    types: [created]
  push:
    branches: ["*"]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on linux
        run: g++ bmp2ds.cpp -std=c++11 -o bmp2ds
      - name: "Publish build to GH Actions"
        uses: actions/upload-artifact@v2
        with:
          path: bmp2ds
          name: "linux"
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on macOS
        run: g++ bmp2ds.cpp -std=c++11 -o bmp2ds
      - name: "Publish build to GH Actions"
        uses: actions/upload-artifact@v2
        with:
          path: bmp2ds
          name: "macos"
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on Windows
        shell: bash
        run: g++ bmp2ds.cpp -std=c++11 -o bmp2ds.exe
      - name: "Publish build to GH Actions"
        uses: actions/upload-artifact@v2
        with:
          path: bmp2ds.exe
          name: "windows"
  publish:
    runs-on: ubuntu-latest
    name: Publish builds
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: [linux, macos, windows]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload builds
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: |
          ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)

          for file in ${{ github.workspace }}/build/*; do
            AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
            CONTENT_LENGTH="Content-Length: $(stat -c%s $file)"
            CONTENT_TYPE="Content-Type: application/7z-x-compressed"
            UPLOAD_URL="https://uploads.github.com/repos/${{ github.repository }}/releases/$ID/assets?name=$(basename $file)"

            curl -XPOST -H "$AUTH_HEADER" -H "$CONTENT_LENGTH" -H "$CONTENT_TYPE" --upload-file "$file" "$UPLOAD_URL"
          done
